name: acid
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy-base=1.15.4
  - pytorch=1.4.0
  - pip
  - pip:
    - scikit-learn==0.24.2
    - h5py==2.9.0
    - plyfile==0.7
    - polyscope==1.2.0
    - trimesh==2.37.7
    - cython==0.29.2
    - imageio==2.4.1
    - numpy==1.15.4
    - matplotlib==3.0.3
    - pandas==0.23.4
    - pillow==5.3.0
    - pytest==4.0.2
    - pyyaml==3.13
    - scikit-image==0.14.1
    - scipy==1.5.2
    - tensorboardx==1.4
    - torchvision==0.2.1
    - tqdm==4.28.1
    - trimesh==2.37.7

# python=3.7.10
# conda install -c conda-forge  matplotlib-base=3.0.3